deployment:
  tasks:
    - export DEPLOYPATH=/home/username/tm.shahriarsadat.com
    - /bin/cp -r * $DEPLOYPATH
    - /usr/local/bin/php $DEPLOYPATH/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
    - /usr/local/bin/npm install --production=false
    - /usr/local/bin/npm run build
